import React, { useState } from 'react';
import { SantaVerdict } from '../types';

interface VerdictCardProps {
  verdict: SantaVerdict;
  imageUrl: string | null;
  loadingImage: boolean;
}

const VerdictCard: React.FC<VerdictCardProps> = ({ verdict, imageUrl, loadingImage }) => {
  const [showSuggestions, setShowSuggestions] = useState(false);
  const isNaughty = verdict.verdict === 'Naughty';
  const hasGifts = verdict.score > 40 && verdict.suggested_gifts && verdict.suggested_gifts.length > 0;

  return (
    <div className="max-w-4xl w-full mx-auto mt-8 animate-fade-in-up">
      <div className={`relative overflow-hidden rounded-2xl border-4 shadow-2xl ${
        isNaughty ? 'border-santa-coal bg-slate-900' : 'border-santa-red bg-red-950'
      }`}>
        
        {/* Header */}
        <div className={`p-6 text-center ${isNaughty ? 'bg-santa-coal' : 'bg-santa-red'}`}>
          <h2 className="text-4xl md:text-6xl font-santa font-bold text-white tracking-wider">
            {verdict.verdict.toUpperCase()}!
          </h2>
          <p className="text-santa-gold font-bold text-lg mt-2 uppercase tracking-widest">
            {verdict.title}
          </p>
        </div>

        <div className="flex flex-col md:flex-row">
          {/* Text Content */}
          <div className="flex-1 p-8 space-y-6">
            <div>
              <h3 className="text-santa-gold font-santa text-2xl mb-2">Santa's Reasoning</h3>
              <p className="text-lg leading-relaxed text-slate-200 italic">
                "{verdict.reasoning}"
              </p>
            </div>

            <div className="flex items-center space-x-4">
              <div className="flex-1">
                <div className="flex justify-between mb-1">
                  <span className="text-sm font-bold text-slate-400">NAUGHTY</span>
                  <span className="text-sm font-bold text-santa-gold">SCORE: {verdict.score}/100</span>
                  <span className="text-sm font-bold text-slate-400">NICE</span>
                </div>
                <div className="w-full bg-slate-800 rounded-full h-4">
                  <div 
                    className={`h-4 rounded-full transition-all duration-1000 ${
                      isNaughty ? 'bg-red-600' : 'bg-green-500'
                    }`}
                    style={{ width: `${verdict.score}%` }}
                  ></div>
                </div>
              </div>
            </div>

            <div className="pt-4 border-t border-white/10">
              <h4 className="text-sm text-slate-400 uppercase tracking-wide mb-1">Incoming Delivery</h4>
              <p className="text-white font-medium">{verdict.gift_description}</p>
            </div>
          </div>

          {/* Image Content */}
          <div className="w-full md:w-1/2 min-h-[300px] bg-black/40 flex items-center justify-center relative border-t md:border-t-0 md:border-l border-white/10">
            {loadingImage && (
              <div className="flex flex-col items-center justify-center text-center p-6 space-y-4">
                <div className="w-12 h-12 border-4 border-santa-gold border-t-transparent rounded-full animate-spin"></div>
                <p className="text-santa-gold font-santa text-xl animate-pulse">
                  Elves are crafting your item...<br/>
                  <span className="text-sm font-sans text-slate-400">(Running Nano Banana)</span>
                </p>
              </div>
            )}
            
            {!loadingImage && imageUrl && (
              <div className="relative w-full h-full group">
                <img 
                  src={imageUrl} 
                  alt="Generated Gift or Coal" 
                  className="w-full h-full object-cover min-h-[350px]"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex items-end p-4">
                  <span className="text-white text-sm">Generated by Gemini 2.5 Flash Image</span>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Real World Gift Ideas Footer */}
        {hasGifts && (
          <div className="border-t border-white/10 bg-slate-900/50">
            <button 
              onClick={() => setShowSuggestions(!showSuggestions)}
              className="w-full py-4 px-6 text-center text-santa-gold font-bold hover:bg-white/5 transition-colors flex items-center justify-center gap-2 group"
            >
              <span className={`transform transition-transform duration-200 ${showSuggestions ? 'rotate-180' : ''}`}>▼</span>
              Know this person? Want some practical gift ideas?
            </button>
            
            {showSuggestions && (
              <div className="p-6 pt-2 border-t border-white/5 bg-slate-900/80 animate-in fade-in slide-in-from-top-2 duration-300">
                <h4 className="text-sm text-santa-gold uppercase tracking-wide mb-3 flex items-center flex-wrap gap-2">
                  <span>🛍️</span> 
                  Real World Gift Ideas 
                  {isNaughty && <span className="normal-case opacity-70 font-normal ml-1">(because they might still deserve a little something)</span>}
                </h4>
                <div className="space-y-3">
                  {verdict.suggested_gifts?.map((gift, idx) => (
                    <div key={idx} className="bg-slate-800/80 p-3 rounded-lg border border-white/5 flex flex-col sm:flex-row sm:items-center justify-between gap-3 shadow-sm">
                      <div>
                        <p className="font-bold text-white text-sm">{gift.item_name}</p>
                        <p className="text-xs text-slate-400">{gift.reason}</p>
                      </div>
                      <a 
                        href={`https://www.google.com/search?tbm=shop&q=${encodeURIComponent(gift.item_name)}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs bg-santa-gold text-santa-darkRed font-bold px-3 py-2 rounded hover:bg-yellow-400 transition-colors whitespace-nowrap text-center shadow-md hover:shadow-lg"
                      >
                        Find on Google
                      </a>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

      </div>
    </div>
  );
};

export default VerdictCard;